python main.py --path /mnt/e/3DOPFormerDataset/lidar_pcap/lidar_indoor_canteen_floor_1-filter.pcap --out-dir /mnt/e/3DOPFormerDataset/lidar --config params.yaml
python main.py --path /mnt/e/3DOPFormerDataset/lidar_pcap/lidar_indoor_canteen_floor_2-filter.pcap --out-dir /mnt/e/3DOPFormerDataset/lidar --config params.yaml
python main.py --path /mnt/e/3DOPFormerDataset/lidar_pcap/lidar_indoor_canteen_floor_3-filter.pcap --out-dir /mnt/e/3DOPFormerDataset/lidar --config params.yaml
python main.py --path /mnt/e/3DOPFormerDataset/lidar_pcap/lidar_indoor_fengyu-filter.pcap --out-dir /mnt/e/3DOPFormerDataset/lidar --config params.yaml
python main.py --path /mnt/e/3DOPFormerDataset/lidar_pcap/lidar_indoor_huiwen_floor_1-filter.pcap --out-dir /mnt/e/3DOPFormerDataset/lidar --config params.yaml
python main.py --path /mnt/e/3DOPFormerDataset/lidar_pcap/lidar_indoor_huiwen_floor_2-filter.pcap --out-dir /mnt/e/3DOPFormerDataset/lidar --config params.yaml
python main.py --path /mnt/e/3DOPFormerDataset/lidar_pcap/lidar_indoor_library_floor_2-filter.pcap --out-dir /mnt/e/3DOPFormerDataset/lidar --config params.yaml
python main.py --path /mnt/e/3DOPFormerDataset/lidar_pcap/lidar_indoor_museum_floor_2-filter.pcap --out-dir /mnt/e/3DOPFormerDataset/lidar --config params.yaml
python main.py --path /mnt/e/3DOPFormerDataset/lidar_pcap/lidar_indoor_museum_floor_4-filter.pcap --out-dir /mnt/e/3DOPFormerDataset/lidar --config params.yaml
python main.py --path /mnt/e/3DOPFormerDataset/lidar_pcap/lidar_indoor_N5_floor_1_north-filter.pcap --out-dir /mnt/e/3DOPFormerDataset/lidar --config params.yaml
python main.py --path /mnt/e/3DOPFormerDataset/lidar_pcap/lidar_indoor_N5_floor_1_south-filter.pcap --out-dir /mnt/e/3DOPFormerDataset/lidar --config params.yaml
python main.py --path /mnt/e/3DOPFormerDataset/lidar_pcap/lidar_indoor_N5_floor_1-filter.pcap --out-dir /mnt/e/3DOPFormerDataset/lidar --config params.yaml
python main.py --path /mnt/e/3DOPFormerDataset/lidar_pcap/lidar_indoor_N5_floor_2-filter.pcap --out-dir /mnt/e/3DOPFormerDataset/lidar --config params.yaml
python main.py --path /mnt/e/3DOPFormerDataset/lidar_pcap/lidar_indoor_N7_floor_1-filter.pcap --out-dir /mnt/e/3DOPFormerDataset/lidar --config params.yaml
python main.py --path /mnt/e/3DOPFormerDataset/lidar_pcap/lidar_indoor_N7_floor_2-filter.pcap --out-dir /mnt/e/3DOPFormerDataset/lidar --config params.yaml
python main.py --path /mnt/e/3DOPFormerDataset/lidar_pcap/lidar_indoor_shoppingmall_floor_1-filter.pcap --out-dir /mnt/e/3DOPFormerDataset/lidar --config params.yaml
python main.py --path /mnt/e/3DOPFormerDataset/lidar_pcap/lidar_indoor_shoppingmall_floor_2-filter.pcap --out-dir /mnt/e/3DOPFormerDataset/lidar --config params.yaml
python main.py --path /mnt/e/3DOPFormerDataset/lidar_pcap/lidar_indoor_zhensheng-filter.pcap --out-dir /mnt/e/3DOPFormerDataset/lidar --config params.yaml